import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Create.module.scss";
import Flashcard from "components/Flashcard/Flashcard";
import Category from "components/Category/Category";
import Button from "components/Button/Button";

export default function Create() {
  
  const [word, setWord] = useState("");
  const [description, setDescription] = useState("");
  const [error, setError] = useState(false);
  const [btnPath, setBtnPath] = useState("");
  const [category, setCategory] = useState(null)
  const handleNewCard = () => {
    if (!word || !description) {
      setError(true);
      setBtnPath('')
    }
  };

  return (
    <>
      <Head>
        <title>fishky | create new flashcard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Flashcard>
          <form className={styles.form} onSubmit={handleNewCard}>
            <Category />
            <input
              type="text"
              name="front"
              placeholder=" enter front..."
              className={styles.front}
              onChange={(e) => setWord(e.target.value)}
            ></input>
            <input
              type="text"
              name="reverse"
              placeholder="enter reverse..."
              className={styles.back}
              onChange={(e) => setDescription(e.target.value)}
            ></input>
            <Button
              buttonType="submit"
              buttonPath={btnPath}
              buttonText="create"
            />
            {error && <p>fill both inputs</p>}
          </form>
        </Flashcard>
      </main>
    </>
  );
}
