import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Flashcard from "components/Flashcard/Flashcard";
import Button from "components/Button/Button";
import useAuth from "hooks/useAuth";

export default function Home() {
  const { logout } = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={logout}>logout</button>
        <Flashcard>
          <div className={styles.options}>
            <Button
              buttonType="button"
              buttonText="create"
              buttonPath="/create"
            />
            <Button
              buttonType="button"
              buttonText="learn"
              buttonPath="/learn"
            />
          </div>
        </Flashcard>
      </main>
    </>
  );
}
