import React from "react";
import Head from "next/head";
import styles from "../styles/Learn.module.scss";
import Flashcard from "components/Flashcard/Flashcard";
import Category from "components/Category/Category";
import Button from "components/Button/Button";

export default function Learn() {
  return (
    <>
      <Head>
        <title>fishky | learn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Flashcard>
          <div className={styles.buttons}>
            <Category />
            <Button
              buttonType="button"
              buttonText="start"
              buttonPath="/learningMode"
            />
          </div>
        </Flashcard>
      </main>
    </>
  );
}
